extends:
  - prettier
  - plugin:import/recommended
  - plugin:import/typescript

parser: "@typescript-eslint/parser"

settings:
  import/resolver:
    typescript: true
    node: true
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx

rules:
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
